### ISSUE TITLE
Add some outputs

### ISSUE THREAD

**Issue by Vermyndax** [spotinst/terraform-spotinst-ocean-spark#34]
We're starting to use this module to provision some Ocean for Spark clusters. It would be great if there were some outputs that could be consumed elsewhere by lambdas/step functions. For example, we need to provide the URL to the Ocean for Spark cluster to a lambda script. It would be much more portable if this module provided the URL as an output.

**Comment by Z4ck404** [comment]
Hey @Vermyndax, 

Do you mean the ocean_spark endpoint to submit apps for example ? 

That's actually a static `url` that you can find in the [ocean spark docs](https://docs.spot.io/ocean-spark/getting-started/run-your-first-app?id=run-pi-app), that you can construct using [output](https://github.com/spotinst/terraform-spotinst-ocean-spark/blob/main/output.tf) `ocean_spark_id` that we just added in the version `v2.0.1` and your `spotinst_account`. 

Something like : 
`https://api.spotinst.io/ocean/spark/cluster/${module.ocean-spark.ocean_spark_id}/app?accountId=${var.spotinst_account}
`
