### ISSUE TITLE
Error: from-vpc-eks-blueprint

### ISSUE THREAD

**Issue by rocavalcante** [spotinst/terraform-spotinst-ocean-spark#50]
The main.tf file in the directory from-vpc-eks-blueprint has an error on the line:

source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons"

because it contains two //

**Comment by Z4ck404** [comment]
Thanks for reporting it. The example will be fixed and update to use this module insteat to install the addons https://registry.terraform.io/modules/aws-ia/eks-blueprints-addons/aws/latest

**Comment by Z4ck404** [comment]
The example is updated @rocavalcante https://github.com/spotinst/terraform-spotinst-ocean-spark/blob/main/examples/from-vpc-eks-blueprint/main.tf, feel free to reach out if you still encounter issues. Thanks
